# Importer Configuration.

table-sql = "create table t(a int primary key, b double, c varchar(10), d date unique, e time unique, f timestamp unique, g date unique, h datetime unique, i year unique);"

index-sql = "create unique index u_b on t(b);"

log-level = "info"

worker-count = 1
job-count = 10
batch = 1

[db]
host = "127.0.0.1"
user = "root"
password = ""
name = "test"
port = 3306
